# Generated by Django 3.0.8 on 2020-11-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-active']},
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='start_date',
        ),
    ]
