# Generated by Django 3.0.8 on 2020-11-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_auto_20201104_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
