# Generated by Django 3.0.8 on 2020-11-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_schema_results'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schema',
            old_name='results',
            new_name='result',
        ),
    ]
