# Generated by Django 3.0.8 on 2020-11-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_auto_20201117_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2020-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
