# Generated by Django 3.0.8 on 2020-11-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_auto_20201117_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
