# Generated by Django 3.0.8 on 2020-12-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_auto_20201126_2206'),
        ('campaigns', '0009_auto_20201130_2053'),
    ]

    operations = [
    ]
