# Generated by Django 3.0.8 on 2021-01-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_auto_20201221_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='object_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
