# Generated by Django 3.0.8 on 2020-10-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201005_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='created_at',
            new_name='date',
        ),
    ]
