# Generated by Django 3.0.8 on 2020-10-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201015_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('CRIR', 'Repair in Component'), ('SRIR', 'Repair in Subsystem'), ('CRCE', 'Replace in Component'), ('SRCE', 'Replace in Subsystem'), ('WAW', 'Withdraw'), ('RLL', 'Reinstall'), ('FIL', 'Failure in Failure Mode'), ('CIL', 'Failure in Component'), ('SIL', 'Failure in Subsystem')], default='WAW', max_length=14),
        ),
    ]
