# Generated by Django 3.0.8 on 2020-08-31 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csvs')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('bop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bops.Bop')),
            ],
        ),
    ]
