# Generated by Django 3.0.8 on 2020-08-27 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csv',
            old_name='active',
            new_name='read',
        ),
    ]
