# Generated by Django 3.0.8 on 2020-10-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='object_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('RIR', 'Repair'), ('RCE', 'Replace'), ('WAW', 'Withdraw'), ('RLL', 'Reinstall'), ('FIL', 'Failure in Failure Mode'), ('CIL', 'Failure in Component'), ('SIL', 'Failure in Subsystem')], default='RIR', max_length=3),
        ),
    ]
