version: '3.7'

services:
  web:
    container_name: bop-web
    build: app
    volumes:
      - static_data:/vol/web
    ports:
      - 851:8000
    env_file:
      - .env.prod
    depends_on:
      - db

  proxy:
    container_name: bop-proxy
    build:
      context: nginx
    volumes:
      - static_data:/vol/static
    ports:
      - "7654:8080"
    depends_on:
      - web

  db:
    container_name: bop-database
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db

  redis:
    container_name: bop-redis
    image: redis:latest

volumes:
  postgres_data:
  static_data:
