version: "3.7"

services:
  app:
    container_name: bop-app
    build: ./app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8001:8000
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    container_name: bop-db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=bop_database

  cache:
    container_name: bop-cache
    image: redis:latest

  celery:
    build: ./app
    command: sh -c "celery -A bop worker -l info"
    restart: always
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      - db
      - cache
    env_file:
      - .env.dev

  celery-beat:
    build: ./app
    command: sh -c "celery -A proj beat -l info"
    restart: always
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      - db
      - cache
      - celery

    env_file:
      - .env.dev
volumes:
  postgres_data:
