version: '3.3'

services:
  app:
    container_name: bop-app
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 851:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: bop-database
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=bop_database

  redis:
    container_name: bop-redis
    image: redis:latest

volumes:
  postgres_data:
