# Generated by Django 3.0.8 on 2020-10-15 16:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bops', '0001_initial'),
        ('failuremodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('tests', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateField(blank=True, default=None, null=True)),
                ('bop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testgroup', to='bops.Bop')),
                ('failure_modes', models.ManyToManyField(related_name='testgroup', related_query_name='testgroup', to='failuremodes.FailureMode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestGroupHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('failure_modes', models.TextField()),
                ('tests', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(choices=[('Created', 'Created'), ('Updated', 'Updated'), ('Deleted', 'Deleted')], default='Updated', max_length=7)),
                ('test_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='test_groups.TestGroup')),
            ],
        ),
        migrations.CreateModel(
            name='TestGroupDummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('tests', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateField(blank=True, default=None, null=True)),
                ('bop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testgroupdummy', to='bops.Bop')),
                ('failure_modes', models.ManyToManyField(related_name='testgroupdummy', related_query_name='testgroupdummy', to='failuremodes.FailureMode')),
                ('test_group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_groups.TestGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
