# Generated by Django 3.0.8 on 2020-10-02 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bops', '0001_initial'),
        ('test_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testgroup',
            name='bop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testgroup', to='bops.Bop'),
        ),
        migrations.AlterField(
            model_name='testgroupdummy',
            name='bop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testgroupdummy', to='bops.Bop'),
        ),
        migrations.CreateModel(
            name='TestSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('test_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='test_groups.TestGroup')),
            ],
        ),
    ]
