# Generated by Django 3.0.8 on 2020-09-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testgroup',
            name='start_date',
            field=models.DateField(default='2020-02-02'),
            preserve_default=False,
        ),
    ]
