# Generated by Django 3.0.8 on 2020-10-02 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_auto_20201002_0131'),
        ('test_groups', '0002_auto_20201002_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testschedule',
            name='test_group',
        ),
        migrations.AddField(
            model_name='testschedule',
            name='phase',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaigns.Phase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testschedule',
            name='test_groups',
            field=models.ManyToManyField(related_name='test_schedules', to='test_groups.TestGroup'),
        ),
    ]
