# Generated by Django 3.0.8 on 2020-09-11 14:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_groups', '0003_auto_20200910_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testgroup',
            name='tests',
        ),
        migrations.AddField(
            model_name='testgroup',
            name='tests',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
