# Generated by Django 3.0.8 on 2020-10-05 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_auto_20201002_0131'),
        ('test_groups', '0003_auto_20201002_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testschedule',
            name='phase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='campaigns.Phase'),
        ),
    ]
