# Generated by Django 3.0.8 on 2020-09-15 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_groups', '0004_auto_20200911_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='testgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2020-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='TestGroupHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_groups.TestGroup')),
            ],
        ),
    ]
