# Generated by Django 3.0.8 on 2020-09-15 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_groups', '0005_auto_20200915_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testgrouphistory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='testgrouphistory',
            name='id',
        ),
        migrations.AddField(
            model_name='testgrouphistory',
            name='testgroup_ptr',
            field=models.OneToOneField(auto_created=True, default=28, on_delete=django.db.models.deletion.CASCADE,
                                       parent_link=True, primary_key=True, serialize=False, to='test_groups.TestGroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testgrouphistory',
            name='test_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='test_groups.TestGroup'),
        ),
    ]
