# Generated by Django 3.0.8 on 2020-09-15 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_groups', '0007_auto_20200915_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testgrouphistory',
            old_name='test_group_id',
            new_name='bop_id',
        ),
        migrations.AddField(
            model_name='testgrouphistory',
            name='test_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='test_groups.TestGroup'),
            preserve_default=False,
        ),
    ]
