# Generated by Django 3.0.8 on 2020-09-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_groups', '0008_auto_20200915_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testgrouphistory',
            name='bop_id',
        ),
    ]
