# Generated by Django 3.0.8 on 2020-09-16 13:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bops', '0001_initial'),
        ('failuremodes', '0002_remove_failuremode_groups'),
        ('test_groups', '0010_auto_20200915_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testgroup',
            name='failure_modes',
            field=models.ManyToManyField(related_name='test_groups_testgroup_related', related_query_name='test_groups_testgroups', to='failuremodes.FailureMode'),
        ),
        migrations.CreateModel(
            name='TestGroupDummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('tests', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateField(blank=True, default=None, null=True)),
                ('bop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bops.Bop')),
                ('failure_modes', models.ManyToManyField(related_name='test_groups_testgroupdummy_related', related_query_name='test_groups_testgroupdummys', to='failuremodes.FailureMode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
