# Generated by Django 3.0.8 on 2020-09-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('failuremodes', '0002_remove_failuremode_groups'),
        ('test_groups', '0011_auto_20200916_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testgroup',
            name='failure_modes',
            field=models.ManyToManyField(related_name='testgroup_related', related_query_name='testgroups', to='failuremodes.FailureMode'),
        ),
        migrations.AlterField(
            model_name='testgroupdummy',
            name='failure_modes',
            field=models.ManyToManyField(related_name='testgroupdummy_related', related_query_name='testgroupdummys', to='failuremodes.FailureMode'),
        ),
    ]
