# Generated by Django 3.0.8 on 2020-09-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('failuremodes', '0002_remove_failuremode_groups'),
        ('test_groups', '0012_auto_20200916_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testgroup',
            name='failure_modes',
            field=models.ManyToManyField(related_name='testgroup', related_query_name='testgroup', to='failuremodes.FailureMode'),
        ),
        migrations.AlterField(
            model_name='testgroupdummy',
            name='failure_modes',
            field=models.ManyToManyField(related_name='testgroupdummy', related_query_name='testgroupdummy', to='failuremodes.FailureMode'),
        ),
    ]
