# Generated by Django 3.0.8 on 2020-09-17 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_groups', '0013_auto_20200916_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='testgroupdummy',
            name='test_group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_groups.TestGroup'),
        ),
    ]
