# Generated by Django 3.0.8 on 2020-09-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(choices=[('1', 'Descend'), ('2', 'Connect'), ('3', 'Drilling'), ('4', 'Disconnect')], default='1')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('duration', models.FloatField()),
            ],
        ),
    ]
