# Generated by Django 3.0.8 on 2020-07-29 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bops', '0001_initial'),
        ('campaigns', '0002_auto_20200729_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='bop_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bops.Bop'),
            preserve_default=False,
        ),
    ]
