# Generated by Django 3.0.8 on 2020-08-21 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bops', '0002_auto_20200819_1511'),
        ('campaigns', '0002_auto_20200819_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-active', '-start_date']},
        ),
        migrations.AddField(
            model_name='campaign',
            name='well_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='bop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='bops.Bop'),
        ),
    ]
