# Generated by Django 3.0.8 on 2020-10-13 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_groups', '0001_initial'),
        ('campaigns', '0002_auto_20201012_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='campaigns.Schema'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='test_groups',
            field=models.ManyToManyField(related_name='test_groups', to='test_groups.TestGroup'),
        ),
    ]
