# Generated by Django 3.0.8 on 2020-09-28 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='campaigns.Campaign'),
            preserve_default=False,
        ),
    ]
