# Generated by Django 3.0.8 on 2020-09-28 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bops', '0001_initial'),
        ('campaigns', '0003_phase_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='bop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='bops.Bop'),
        ),
    ]
