# Generated by Django 3.0.8 on 2020-07-29 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20200729_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='bop_id',
            new_name='bop',
        ),
    ]
