# Generated by Django 3.0.8 on 2020-08-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20200821_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='rig_name',
            field=models.CharField(default='no name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='well_name',
            field=models.CharField(default='noname', max_length=100),
            preserve_default=False,
        ),
    ]
