# Generated by Django 3.0.8 on 2020-10-02 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20200928_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='step',
            field=models.IntegerField(choices=[('1', 'Descend'), ('2', 'Connect'), ('3', 'Drilling'), ('4', 'Disconnect'), ('5', 'Test')], default='1'),
        ),
    ]
