# Generated by Django 3.0.8 on 2020-09-03 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bops', '0002_delete_cut'),
        ('failuremodes', '0002_auto_20200901_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField()),
                ('order', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('failure_modes', models.ManyToManyField(to='failuremodes.FailureMode')),
                ('safety_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuts', to='bops.SafetyFunction')),
            ],
        ),
    ]
