# Generated by Django 3.0.8 on 2020-09-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cut',
            name='value',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
