# Generated by Django 3.0.8 on 2020-09-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cut',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cut',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='cut',
            name='value',
        ),
        migrations.RemoveField(
            model_name='cut',
            name='failure_modes',
        ),
        migrations.AddField(
            model_name='cut',
            name='failure_modes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
