# Generated by Django 3.0.8 on 2020-09-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('failuremodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='failuremode',
            options={'ordering': ['code']},
        ),
    ]
