# Generated by Django 3.0.8 on 2020-10-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bop',
            name='model',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bop',
            name='rig',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Rig',
        ),
    ]
