# Generated by Django 3.0.8 on 2020-11-30 21:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bops', '0002_auto_20201029_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='bop',
            name='matrix',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
