# Generated by Django 3.0.8 on 2021-01-05 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bops', '0004_certification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='code',
        ),
    ]
