# Generated by Django 3.0.8 on 2021-01-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bops', '0005_remove_certification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bop',
            name='is_outdated',
            field=models.BooleanField(default=False),
        ),
    ]
