# Generated by Django 3.0.8 on 2020-11-17 19:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testgroup',
            name='tests',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testgroupdummy',
            name='tests',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
