# Generated by Django 3.0.8 on 2020-12-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_groups', '0002_auto_20201117_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='testgroup',
            name='pressure_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testgroupdummy',
            name='pressure_test',
            field=models.BooleanField(default=False),
        ),
    ]
