# Generated by Django 3.0.8 on 2020-08-19 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subsystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('bop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsystems', to='bops.Bop')),
            ],
        ),
        migrations.CreateModel(
            name='FailureMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failures_mode', to='bops.Component')),
                ('failure_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='failure_children', to='bops.FailureMode')),
            ],
        ),
        migrations.CreateModel(
            name='Cut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failures_mode', models.TextField()),
                ('safety_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bops.SafetyFunction')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='subsystem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='bops.Subsystem'),
        ),
    ]
