# Generated by Django 3.0.8 on 2020-08-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bops', '0002_auto_20200819_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bop',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
