# Generated by Django 3.0.8 on 2020-08-25 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bops', '0003_auto_20200821_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='bop',
            name='description',
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('bop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='bops.Bop')),
            ],
        ),
        migrations.AddField(
            model_name='bop',
            name='rig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bops.Rig'),
        ),
    ]
