# Generated by Django 3.0.8 on 2020-09-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bops', '0003_testgroup_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testgroup',
            name='code',
            field=models.BigIntegerField(unique=True),
        ),
    ]
