# Generated by Django 3.0.8 on 2020-09-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bops', '0004_auto_20200904_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testgroup',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
