# Generated by Django 3.0.8 on 2020-09-04 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bops', '0005_auto_20200904_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyfunction',
            name='bop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='safety_functions', to='bops.Bop'),
            preserve_default=False,
        ),
    ]
