# Generated by Django 3.0.8 on 2020-08-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bops', '0005_auto_20200826_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testgroup',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='testgroup',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='testgroup',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testgroup',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
