# Generated by Django 3.0.8 on 2020-08-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bops', '0006_auto_20200826_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bop',
            name='code',
        ),
        migrations.AlterField(
            model_name='testgroup',
            name='tests',
            field=models.ManyToManyField(related_name='groups', to='bops.Test'),
        ),
    ]
