# Generated by Django 3.0.8 on 2020-08-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bops', '0007_auto_20200826_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subsystem',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
