# Generated by Django 3.0.8 on 2020-08-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bops', '0008_auto_20200827_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='failuremode',
            name='diagnostic_coverage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
