# Generated by Django 3.0.8 on 2020-08-27 03:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bops', '0010_auto_20200827_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failuremode',
            name='distribution',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
