# Generated by Django 3.0.8 on 2020-08-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bops', '0011_auto_20200827_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='id',
        ),
        migrations.RemoveField(
            model_name='failuremode',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subsystem',
            name='id',
        ),
        migrations.AlterField(
            model_name='component',
            name='code',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='failuremode',
            name='code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subsystem',
            name='code',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
