# Generated by Django 3.0.8 on 2020-08-31 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsystem',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('bop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsystems', to='bops.Bop')),
            ],
        ),
    ]
