# Generated by Django 3.0.8 on 2020-10-29 16:56

from django.db import migrations
from django.contrib.auth.models import User, Group


def apply_migration(apps, schema_editor):

    admin_group = Group.objects.create(name='Admin')
    user = User.objects.create_superuser('admin', 'admin@example.com', 'pwd')

    user.groups.add(admin_group)


def revert_migration(apps, schema_editor):
    User.objects.filter(name='admin').delete()
    Group.objects.filter(name='Admin').delete()


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [migrations.RunPython(apply_migration, revert_migration)]
