# Generated by Django 3.0.8 on 2020-07-30 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bops', '0001_initial'),
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='bop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bops.Bop'),
        ),
    ]
